# Loading dataset

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Combined_dataset.csv")

# Data Exploration

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
df.shape

(1000, 24)

In [6]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 4.9 MB

In [8]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

# Handling missing Values

In [9]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [10]:
df["discount"]=df["discount"].fillna(df["discount"].mean())

In [11]:
df["what_customers_said"]=df["what_customers_said"].fillna("No review")
df["seller_name"]=df["seller_name"].fillna("No seller name")
df["videos"]=df["videos"].fillna("No videos")
df["seller_information"]=df["seller_information"].fillna("No information")
df["variations"]=df["variations"].fillna("No variation")

In [12]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

# Filtering Rows (pandas)

In [19]:
high_rating=df[df["rating"]>4]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,amount_saved
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.000000,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No review,No seller name,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",No information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.000000,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No review,No seller name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No information,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.000000,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No review,No seller name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No information,No variation,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.000000,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No review,No seller name,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No videos,No information,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,No review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No videos,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,0.0

In [20]:
high_discount=df[df["discount"]>50]
high_discount.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,amount_saved
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.000000,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,No review,No seller name,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",No information,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.000000,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No review,No seller name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No information,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.000000,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No review,No seller name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No information,No variation,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,No review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No videos,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,0.0
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.000000,1399.0,INR,http://assets.myntassets.com/assets/images/198...,...,No review,No seller name,"[{""size"":""Onesize""}]",No videos,No information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels,0.0

# Removing Duplicates

In [13]:
df.duplicated().sum()

np.int64(0)

# Derived Column

In [14]:
df[["initial_price","final_price"]].dtypes

initial_price    int64
final_price        str
dtype: object

In [15]:
df["final_price"] = (
    df["final_price"]
    .str.replace('"', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

In [16]:
df["final_price"] = df["final_price"].astype(float)

In [17]:
df["amount_saved"] = df["initial_price"] - df["final_price"]

In [18]:
df[["initial_price","final_price","amount_saved"]].tail()

     initial_price  final_price  amount_saved
995          11890      11890.0           0.0
996           8900       8900.0           0.0
997           7950       7950.0           0.0
998           3295       2636.0         659.0
999            699        699.0           0.0

# Filtering Rows (pyspark)

In [31]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import avg
spark=SparkSession.builder \
    .appName("CEI_Task1") \
    .getOrCreate()
spark_df=spark.createDataFrame(df)

In [4]:
spark_df.show(5)

+----------+--------------+--------------------+------+-------------+-------------+--------+-----------+---------+------+--------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|product_id|         title| product_description|rating|ratings_count|initial_price|discount|final_price| currency|images|    delivery_options|     product_details|         breadcrumbs|product_specifications|     amount_of_stars| what_customers_said|         seller_name|               sizes|              videos|  seller_information|          variations|          best_offer|         more_offers|            category|
+----------+--------------+--------------------+------+-------------+-------------+--------+-----------+---------+------+--------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|   8376765|   Lino Perros|Women Navy Blue S...|   3.8|           15|         3995|      58|      """₹3|995.00"""|   INR|http://assets.myn...|"[""100% Original...|""Pay on delivery...|  ""Easy 14 days re...|""Try & Buy might...|"{""description""...|""material_and_ca...| dry cloth to rem...|""size_and_fit"":...|"[{""name"":""Acc...|""url"":""https:/...| {""name"":""Women""|""url"":""https:/...|{""name"":""Backp...|
|   9136281|Tommy Hilfiger|Unisex Navy Blue ...|   4.5|           67|         2899|      35|      """₹2|899.00"""|   INR|http://assets.myn...|"[""100% Original...|""Pay on delivery...|  ""Easy 14 days re...|""Try & Buy might...|"{""description""...|""material_and_ca...| dry cloth to rem...|""size_and_fit"":...|"[{""name"":""Acc...|""url"":""https:/...|{""name"":""Unisex""|""url"":""https:/...|{""name"":""Backp...|
|  17633752|         Lavie|Aries Women Pink ...|   4.4|          226|         2999|      65|      """₹2|999.00"""|   INR|http://assets.myn...|"[""100% Original...|""Pay on delivery...|  ""Easy 14 days re...|""Try & Buy might...|"{""description""...| has 1 main compa...|          Zip pocket|   Non-padded bac...|""material_and_ca...|""size_and_fit"":...|"[{""name"":""Acc...|""url"":""https:/...| {""name"":""Women""|
|   1376949|        F Gear|Unisex Navy & Gre...|   4.4|         1052|         1675|      52|      """₹1|675.00"""|   INR|http://assets.myn...|"[""100% Original...|""Pay on delivery...|  ""Easy 14 days re...|""Try & Buy might...|"{""description""...| two padded and a...| one with a slip ...|""material_and_ca...| dry cloth when n...|""size_and_fit"":...|"[{""name"":""Acc...|""url"":""https:/...|{""name"":""Unisex""|
|  13939916|     MYTRIDENT|Men Blue Solid Ba...|   4.7|           12|         2899|      17|      """₹2|899.00"""|   INR|http://assets.myn...|"[""100% Original...|""Pay on delivery...|  ""Easy 14 days re...|""Try & Buy might...|"{""description""...| has a shawl coll...| three-quarter sl...| two patch pocket...| and belt loops o...|""material_and_ca...|""size_and_fit"":...| "[{""name"":""Men""|""url"":""https:/...|
+----------+--------------+--------------------+------+-------------+-------------+--------+-----------+---------+------+--------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
only showing top 5 rows

In [5]:
spark_df.printSchema()

root
 |-- product_id: integer (nullable = true)
 |-- title: string (nullable = true)
 |-- product_description: string (nullable = true)
 |-- rating: double (nullable = true)
 |-- ratings_count: integer (nullable = true)
 |-- initial_price: integer (nullable = true)
 |-- discount: integer (nullable = true)
 |-- final_price: string (nullable = true)
 |-- currency: string (nullable = true)
 |-- images: string (nullable = true)
 |-- delivery_options: string (nullable = true)
 |-- product_details: string (nullable = true)
 |-- breadcrumbs: string (nullable = true)
 |-- product_specifications: string (nullable = true)
 |-- amount_of_stars: string (nullable = true)
 |-- what_customers_said: string (nullable = true)
 |-- seller_name: string (nullable = true)
 |-- sizes: string (nullable = true)
 |-- videos: string (nullable = true)
 |-- seller_information: string (nullable = true)
 |-- variations: string (nullable = true)
 |-- best_offer: string (nullable = true)
 |-- more_offers: string (nullable = true)
 |-- category: string (nullable = true)

In [26]:
spark_df.groupBy("seller_name").count().show()

+--------------------+-----+
|         seller_name|count|
+--------------------+-----+
| has regular styling|   13|
|         5 pockets""|    6|
|""material_and_ca...|    1|
|Lace-ups detailSy...|    1|
| black and whiteP...|    1|
|  no fade navy bl...|    1|
|""size_and_fit"":...|    1|
| energy-returning...|    1|
|""size_and_fit"":...|    1|
|   slip-on closure""|    1|
|  flared sleeve  ...|    1|
| no fade blue jea...|    1|
|             fitness|    1|
|        long sleeves|   14|
|  puff sleeves   ...|    1|
| has a polo colla...|    1|
| follow the fabri...|    1|
|""material_and_ca...|    1|
| light fade navy ...|    1|
| short flared sle...|    1|
+--------------------+-----+
only showing top 20 rows

In [29]:
from pyspark.sql.functions import avg

spark_df.groupBy("seller_name") \
        .agg(avg("rating").alias("average_rating")) \
        .show(20, truncate=False)

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|seller_name                                                                                                                                                                                                                                                                                                                                                                                                                     |average_rating    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| has regular styling                                                                                                                                                                                                                                                                                                                                                                                                            |3.7076923076923074|
| 5 pockets""                                                                                                                                                                                                                                                                                                                                                                                                                    |4.083333333333333 |
|""material_and_care"":""Art Silk. Machine Wash""                                                                                                                                                                                                                                                                                                                                                                                |0.0               |
|Lace-ups detailSynthetic leather upperCushioned footbedTextured and patterned outsoleWarranty: limited warrantyWarranty provided by brand owner/manufacturer""                                                                                                                                                                                                                                                                  |3.9               |
| black and whitePresented in an Iris boxFeatures: Eco friendly""                                                                                                                                                                                                                                                                                                                                                                |4.5               |
|  no fade navy blue jeans   Slim fit                                                                                                                                                                                                                                                                                                                                                                                            |4.3               |
|""size_and_fit"":""The model (height 5'8\"") is wearing a size 28""}"                                                                                                                                                                                                                                                                                                                                                           |0.0               |
| energy-returning feelFitcounter moulded heel counterBOOST midsoleClassic Adidas 3 stripe detail on sidesAdidas branding on tongueWarranty: 3 monthsWarranty provided by brand/manufacturerAbout Men Woven Design Ultraboost 5.0 DNA Running ShoesThe Ultraboost isn't our first performance running shoe to hold appeal in the realm of fashion. It's just one of the most beloved. That's why we made the Ultraboost DNA Shoes|3.9               |
|""size_and_fit"":""I""}"                                                                                                                                                                                                                                                                                                                                                                                                        |3.5               |
| slip-on closure""                                                                                                                                                                                                                                                                                                                                                                                                              |4.3               |
|  flared sleeve   Gathered or pleated detail   Knee length in flounce hem   Georgette fabric   Zip closure  ""                                                                                                                                                                                                                                                                                                                  |4.8               |
| no fade blue jeans512 Slim Tapered fit                                                                                                                                                                                                                                                                                                                                                                                         |4.3               |
| fitness                                                                                                                                                                                                                                                                                                                                                                                                                        |3.7               |
| long sleeves                                                                                                                                                                                                                                                                                                                                                                                                                   |3.7857142857142856|
|  puff sleeves   A-line shape with panelled style   Thread work detail   Ankle length with curved hem   Machine weave regular cotton  ""                                                                                                                                                                                                                                                                                        |4.4               |
| has a polo collar and short leeves""                                                                                                                                                                                                                                                                                                                                                                                           |3.7               |
| follow the fabric care label.""                                                                                                                                                                                                                                                                                                                                                                                                |0.0               |
|""material_and_care"":""Plastic. Wipe with a clean dry cloth""}"                                                                                                                                                                                                                                                                                                                                                                |4.3               |
| light fade navy blue jeansFlared                                                                                                                                                                                                                                                                                                                                                                                               |3.7               |
| short flared sleeves                                                                                                                                                                                                                                                                                                                                                                                                           |4.2               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
only showing top 20 rows

# Cleaned csv

In [33]:
df.to_csv("cleaned_combined_dataset.csv",index=False)